### ISSUE TITLE
Use for csl-styles

### ISSUE THREAD

**Issue by adam3smith** [retorquere/label-gun#6]
I'm thinking of this for CSL styles -- am I correct that all I'd need to do is to put then label-gun.yml into `.github/workflows`?

Do you have a mini description of what this does (if anything other than adding the awaiting feedback tag after owner has posted)?

**Comment by retorquere** [comment]
I'll write a description later today.

**Comment by retorquere** [comment]
A whole lot has become BBT-specific over the course of time. For issues that are labeled with `question` by the issue template, is mostly stays out of the users' way, but for anything else, it checks for the presence of a debug log ID, and first loudly complains by posting a large description, and if that doesn't get a debug log in the next post/edit, mutters on by adding a prompt to every user-posted text.

As it stands, I don't think it's very usable outside BBT, although I'd be happy to generalize a few things (read text from templates, make the debug ID format configurable).

One thing that should be really easy to generalize is "awaiting user input" -- label-gun checks who was the last to post on an issue, and if it's the owner or someone with commit rights, applies the label, and when someone outside that group posts, removes the label.

It currently actively re-opens issues unless an owner/committer closed the issue, and will re-open the issue if any non-owner/comitter posts.

**Comment by adam3smith** [comment]
Yeah, I'm exclusively interested in this

> One thing that should be really easy to generalize is "awaiting user input" -- label-gun checks who was the last to post on an issue, and if it's the owner or someone with commit rights, applies the label, and when someone outside that group posts, removes the label.

Though without the issue reopening. I was looking around for something similar, but couldn't find anything. We would also want this for PRs rather than issues. 

If it's easy enough to just limit functionality to that with a config option, that would be great. Otherwise, I can fork & simplify of course

Support log ID:

**Comment by retorquere** [comment]
I need to do cleanup anyway, I'll take this along.

**Comment by retorquere** [comment]
The cleanup is done, I'm doing tests now, but as a starter: for minimal use, you will want to add

```
on:
  issues:
    types: [opened, edited, closed]
  issue_comment:
    types: [created, edited, closed]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: retorquere/label-gun@main
        with:
          token: ${{ github.token }}
```

which will by default toggle the label `awaiting-user-feedback` on and off depending on whether a non-contributor added the last comment. The label can be set using
```
        with:
          label.awaiting: "some other label"
```
